//
//  NSDictionary+Tasks.m
//  Timus
//
//  Created by Pedro Oliveira on 9/27/13.
//  Copyright (c) 2013 Timus. All rights reserved.
//

#import "NSDictionary+Tasks.h"
#import "NSString+TimeFormatting.h"
#import "ELTask+Common.h"
#import "ELProject+Common.h"
#import "UIImage+Resize.h"

#define kExportDateFormat @"YYYY/MM/dd HH:mm:ss"

@implementation NSDictionary (Tasks)

#pragma mark - Methods

- (NSString*) html
{
    NSArray *projectNames = [self allKeys];
    NSMutableString *content = [[NSMutableString alloc] init];
    
    NSString *parentTableOpenContainer = @"<html><body><br><br><table style='width: min-width: 480px; max-width: 760px; border: none; border-collapse: collapse;' cellspacing='0' borderspacing='1' border='0' spellcheck='true' align='center'><tr><td>";
    
    NSString *generatedByString = NSLocalizedString(@"Generated by <a href=\"http://www.timusapp.com\">Timus</>", @"");
    
    NSString *parentTableCloseContainer = [NSString stringWithFormat:@"</td></tr><tr style='text-align: center;'><td>%@</td></tr></table>", generatedByString];
    
    //Opening table container
    [content appendString:parentTableOpenContainer];
    
    for (NSString *projectName in projectNames) {
        
        NSArray *tasks = self[projectName];
        UIImage *projectImage = [[[[tasks firstObject] project] image] resizedImage:CGSizeMake(100, 100)
                                                               interpolationQuality:kCGInterpolationHigh];
        NSString *projectImageEncoded = nil;
        if (projectImage) {
            projectImageEncoded = [UIImagePNGRepresentation(projectImage) base64EncodedStringWithOptions:NSDataBase64Encoding64CharacterLineLength];
        }
        //Append Table Oppener
        [content appendString:@"<table style='width:100%; border: none; border-collapse: collapse;' cellspacing='0' borderspacing='1' border='0' spellcheck='true' align='center'>"];
        
        //Append Line Opener
        [content appendString:@"<tr>"];
        
        //Append open column project name
        [content appendString:@"<td bgcolor='#7d7e7d' style='letter-spacing: 1px;font-weight: bold;font-size: 16px;background-color: #7d7e7d; color: #FFF; padding: 15px; text-align: center; border-radius: 7px 7px 0 0;' colspan='4'>"];
        
        if (projectImageEncoded) {
            //Append Peoject Image
            [content appendFormat:@"<img src='data:image/png;base64, %@' style='border-radius: 50%% 50%%; height:50px; vertical-align:middle;' /> - ", projectImageEncoded];

        }
        
        //Append Project Name
        [content appendFormat:@"%@", projectName];
        
        //Close column project name
        [content appendString:@"</td>"];
        
        //Close project name row
        [content appendString:@"</tr>"];
        
        //Append Open Row information row
        [content appendString:@"<tr bgcolor='#ecf0f1' style='font-size: 15px;background-color: #EEE; color: #000; text-align: center; font-weight: bold;background-color: #ecf0f1;background: #ffffff;background: -moz-linear-gradient(top,  #ffffff 0%, #f6f6f6 47%, #ededed 100%);background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(47%,#f6f6f6), color-stop(100%,#ededed));background: -webkit-linear-gradient(top,  #ffffff 0%,#f6f6f6 47%,#ededed 100%);background: -o-linear-gradient(top,  #ffffff 0%,#f6f6f6 47%,#ededed 100%);background: -ms-linear-gradient(top,  #ffffff 0%,#f6f6f6 47%,#ededed 100%);background: linear-gradient(to bottom,  #ffffff 0%,#f6f6f6 47%,#ededed 100%);filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ededed',GradientType=0 );'>"];
        
        //Each column with description
        [content appendString:NSLocalizedString(@"<td style='padding: 10px; width: 45%; text-align: center;'>Description</td>",@"")];
        [content appendString:NSLocalizedString(@"<td style='padding: 10px; text-align:center;'>Start date</td>",@"")];
        [content appendString:NSLocalizedString(@"<td style='padding: 10px; text-align:center;'>End date</td>",@"")];
        [content appendString:NSLocalizedString(@"<td style='padding: 10px; text-align:center;'>Duration</td>",@"")];
        
        //Close Information row
        [content appendString:@"</tr>"];
        
        for (ELTask *task in tasks) {
            //Start task information line
            [content appendString:@"<tr style='font-size: 13px;text-align: center; border-bottom: 1px solid #ccc;'>"];
            
            NSDateFormatter *dateFormat = [[NSDateFormatter alloc] init];
            [dateFormat setDateFormat:kExportDateFormat];
            NSString *startDate = [dateFormat stringFromDate:task.creationDate];
            NSString *endDate = [dateFormat stringFromDate:task.presentingEndDate];
            NSString *duration = [NSString timeIndicatorStringWithElapsedSeconds:task.totalWorkTimeInSeconds];
            NSString *taskDetailHtml = [task.displayDetail stringByReplacingOccurrencesOfString:@"\n"
                                                                                     withString:@"<br>"];
            
            //Task information column
            [content appendFormat:@"<td style='padding: 10px; text-align: left;'>%@</td>", taskDetailHtml];
            
            //Task start date column
            [content appendFormat:@"<td style='padding: 10px; text-align:center;'>%@</td>", startDate];
            
            //Task end date column
            [content appendFormat:@"<td style='padding: 10px; text-align:center;'>%@</td>", endDate];
            
            //Task duration column
            [content appendFormat:@"<td style='padding: 10px; text-align:center;'>%@</td>", duration];
            
            //End task information line
            [content appendString:@"</tr>"];
        }
        
        //Append end of Column
        [content appendString:@"</td>"];
        
        //Append end of line
        [content appendString:@"</tr>"];
        
        //Append Table Closer
        [content appendString:@"</table><br/>"];
    }
    
    //Closing table container and add Powered by
    [content appendString:parentTableCloseContainer];
    //Append body and html close tags*/
    [content appendString:@"</body></html>"];
    
    return content;
}


- (NSString*) csv
{
    NSMutableString *content = [NSMutableString stringWithFormat:NSLocalizedString(@"Project;Description;Start Date;End Date;Duration\n", @"")];
    NSArray *projectNames = [self allKeys];
    for (NSString *projectName in projectNames) {
        NSArray *tasks = self[projectName];
        for (ELTask *task in tasks) {
            NSDateFormatter *dateFormat = [[NSDateFormatter alloc] init];
            [dateFormat setDateFormat:kExportDateFormat];
            NSString *startDate = [dateFormat stringFromDate:task.creationDate];
            NSString *endDate = [dateFormat stringFromDate:task.presentingEndDate];
            NSString *duration = [NSString timeIndicatorStringWithElapsedSeconds:task.totalWorkTimeInSeconds];
            [content appendFormat:@"%@;\"%@\";%@;%@;%@\n", projectName, task.displayDetail, startDate, endDate, duration];
        }
    }
    return content;
}

@end
